#!/usr/bin/env python3
"""
Batch quote fetch from Google Finance.

Reads watchlist.json, fetches each ticker, outputs Markdown report.

Usage:
    python3 fetch_batch.py watchlist.json output.md
    python3 fetch_batch.py watchlist.json          # auto-generates output path

watchlist.json format:
    [
        {"ticker": "AAPL", "exchange": "NASDAQ"},
        {"ticker": "2330", "exchange": "TPE"}
    ]
"""
import asyncio
import json
import sys
import os
from datetime import datetime, timezone
from pathlib import Path

# Add lib to path
SKILL_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(SKILL_DIR / "lib"))

from fetch_quote import fetch_quote, PROFILE_PATH  # noqa: E402

# Default output directory (Pigo: 2026-07-07 changed to ~/Downloads/Sotck/)
DEFAULT_OUTPUT_DIR = Path.home() / "Downloads" / "Sotck"


async def fetch_batch(watchlist: list, delay_between: float = 2.0) -> list:
    """
    Fetch quotes for a watchlist.
    
    Args:
        watchlist: list of {"ticker": ..., "exchange": ...}
        delay_between: seconds to wait between requests (default 2.0)
    
    Returns:
        list of quote dicts
    """
    results = []
    for i, item in enumerate(watchlist):
        ticker = item["ticker"]
        exchange = item["exchange"]
        
        print(f"[{i+1}/{len(watchlist)}] Fetching {ticker}:{exchange}...", file=sys.stderr)
        result = await fetch_quote(ticker, exchange)
        results.append(result)
        
        status = result["status"]
        price = result.get("price")
        currency = result.get("currency")
        if price:
            print(f"  ✓ {currency} {price} ({status})", file=sys.stderr)
        else:
            print(f"  ✗ {status}: {result.get('error', 'no data')}", file=sys.stderr)
        
        # Delay between requests to be polite
        if i < len(watchlist) - 1:
            await asyncio.sleep(delay_between)
    
    return results


def render_markdown(results: list, watchlist_path: str = None) -> str:
    """
    Render results as Markdown report.
    
    Sections:
    - Summary (counts)
    - Successful quotes
    - Unavailable quotes
    - Errors
    """
    timestamp = datetime.now(timezone.utc).isoformat()
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    successful = [r for r in results if r["status"] == "ok"]
    unavailable = [r for r in results if r["status"] == "unavailable"]
    errors = [r for r in results if r["status"] == "error"]
    
    md = []
    md.append(f"# Google Finance Quote Report")
    md.append(f"")
    md.append(f"**Generated**: {now_utc}  ")
    if watchlist_path:
        md.append(f"**Watchlist**: `{watchlist_path}`  ")
    md.append(f"**Total tickers**: {len(results)}  ")
    md.append(f"")
    md.append(f"## Summary")
    md.append(f"")
    md.append(f"| Status | Count |")
    md.append(f"|--------|-------|")
    md.append(f"| ✅ OK | {len(successful)} |")
    md.append(f"| ⚠️ Unavailable | {len(unavailable)} |")
    md.append(f"| ❌ Error | {len(errors)} |")
    md.append(f"")
    
    # Successful
    if successful:
        md.append(f"## ✅ Quotes")
        md.append(f"")
        md.append(f"| Ticker | Exchange | Price | Currency | Change | Source | Timestamp |")
        md.append(f"|--------|----------|-------|----------|--------|--------|-----------|")
        for r in successful:
            price_str = f"{r['price']:,.2f}"
            change = r.get('change_pct') or '-'
            md.append(f"| {r['ticker']} | {r['exchange']} | {price_str} | {r['currency']} | {change} | {r['source']} | {r['timestamp']} |")
        md.append(f"")
    
    # Unavailable
    if unavailable:
        md.append(f"## ⚠️ Unavailable (no data)")
        md.append(f"")
        md.append(f"These tickers returned no price data from Google Finance.")
        md.append(f"")
        md.append(f"| Ticker | Exchange | URL |")
        md.append(f"|--------|----------|-----|")
        for r in unavailable:
            md.append(f"| {r['ticker']} | {r['exchange']} | {r['url']} |")
        md.append(f"")
    
    # Errors
    if errors:
        md.append(f"## ❌ Errors")
        md.append(f"")
        md.append(f"| Ticker | Exchange | Error |")
        md.append(f"|--------|----------|-------|")
        for r in errors:
            err = r.get('error', 'unknown')[:100]
            md.append(f"| {r['ticker']} | {r['exchange']} | `{err}` |")
        md.append(f"")
    
    md.append(f"---")
    md.append(f"*Generated by google-finance skill at {timestamp}*")
    
    return "\n".join(md)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} WATCHLIST.json [OUTPUT.md]", file=sys.stderr)
        print(f"", file=sys.stderr)
        print(f"WATCHLIST.json format:", file=sys.stderr)
        print(f'  [{{"ticker": "AAPL", "exchange": "NASDAQ"}}]', file=sys.stderr)
        sys.exit(1)
    
    watchlist_path = sys.argv[1]
    if not os.path.exists(watchlist_path):
        print(f"Error: watchlist file not found: {watchlist_path}", file=sys.stderr)
        sys.exit(1)
    
    with open(watchlist_path) as f:
        watchlist = json.load(f)
    
    if not isinstance(watchlist, list):
        print(f"Error: watchlist must be a list of {{ticker, exchange}}", file=sys.stderr)
        sys.exit(1)
    
    # Determine output path
    if len(sys.argv) >= 3:
        output_path = sys.argv[2]
    else:
        # Auto-generate path under ~/Downloads/Sotck/
        ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        DEFAULT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        output_path = str(DEFAULT_OUTPUT_DIR / f"google-finance-{ts}.md")
    
    # Fetch
    results = asyncio.run(fetch_batch(watchlist))
    
    # Render
    md = render_markdown(results, watchlist_path)
    
    # Write
    with open(output_path, "w") as f:
        f.write(md)
    
    print(f"\n✅ Report written to: {output_path}", file=sys.stderr)
    print(f"   Successful: {sum(1 for r in results if r['status'] == 'ok')}", file=sys.stderr)
    print(f"   Unavailable: {sum(1 for r in results if r['status'] == 'unavailable')}", file=sys.stderr)
    print(f"   Errors: {sum(1 for r in results if r['status'] == 'error')}", file=sys.stderr)

    # Also dump JSON for debugging
    # Use Path.with_suffix() for safety (avoids `str.replace` on multi-dot paths)
    json_path = str(Path(output_path).with_suffix(".json"))
    with open(json_path, "w") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"   JSON: {json_path}", file=sys.stderr)


if __name__ == "__main__":
    main()